### ISSUE TITLE
Just a heads up: go package management is still a mess

### ISSUE THREAD

**Issue by Sam-Izdat** [jwaldrip/odin#21]
This is not a problem with odin but rather a problem with the current state of go package management and versioning that might have unforeseen repercussions down the line. It might be something to consider.

You suggest using gopkg.in to import a specific version of this project, and that works great for single-package libraries but breaks down when the library has its own imports, as when it contains multiple sub-packages and references itself. For example, odin/cli/CLI.go imports "github.com/jwaldrip/odin/cli/values" and this path does not get re-written by gopkg.in. So, if you have API changes for your V2 release, gopkg.in/jwaldrip/odin.v2/cli will still point to the (version-less) github.com/jwaldrip/odin for "values" -- which may or may not be the correct version in the user's GOPATH.

Goop also has limitations, but I don't think they apply here, as anything importing odin will be a main package, pretty much by definition. Goop doesn't seem to offer any good solution, however, to libraries that might be used by other libraries (non-main packages), which will themselves later be imported.

**Comment by apriendeau** [comment]
I am going to say we stick with the traditional go pattern here using `github.com/jwaldrip/odin` and if people want to use Godeps. Thats fine but I have found that `go get ./...` has been the best option for me to keep everything up to date. @jwaldrip does that work?

**Comment by jwaldrip** [comment]
I think that makes perfect sense. This package has no external dependencies (other than for testing), so I don't see any issue.
